[package]
name = "battlezone-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = "0.7"
tokio-tungstenite = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.1"
uuid = { version = "1.0", features = ["v4", "serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "cors"] }
futures-util = "0.3"
dashmap = "5.5"
tokio-util = "0.7"
rand = "0.8"

[dependencies.axum]
version = "0.7"
features = ["ws"] 